import { createInitialState } from "../../../src/seed";
import { today } from "../../../src/appModel";
import type { AppState } from "../../../src/types";
import { MOCK_SERVER } from "./constants";

export const authenticatedState = (): AppState => {
  const base = createInitialState();
  const now = new Date().toISOString();
  const todayKey = today();
  const privateWorkspace = {
    id: "workspace_private_account_owner",
    name: "项目负责人私人区",
    type: "private" as const,
    ownerAccountId: "account_owner",
    createdAt: now,
    updatedAt: now,
  };
  const sharedWorkspace = {
    id: "workspace_e2e",
    name: "E2E 工作区",
    type: "shared" as const,
    ownerAccountId: "account_owner",
    createdAt: now,
    updatedAt: now,
  };
  return {
    ...base,
    auth: {
      status: "authenticated",
      token: "e2e-token",
      expiresAt: "2099-01-01T00:00:00.000Z",
      bootstrapped: true,
      message: "E2E 本地登录",
      workspace: sharedWorkspace,
      workspaces: [privateWorkspace, sharedWorkspace],
      workspaceMemberships: [
        {
          id: "membership_workspace_private_account_owner",
          workspaceId: "workspace_private_account_owner",
          accountId: "account_owner",
          name: "项目负责人",
          email: "owner@example.com",
          role: "owner",
          status: "active",
          createdAt: now,
          updatedAt: now,
        },
        {
          id: "membership_workspace_e2e_account_owner",
          workspaceId: "workspace_e2e",
          accountId: "account_owner",
          name: "项目负责人",
          email: "owner@example.com",
          role: "owner",
          status: "active",
          createdAt: now,
          updatedAt: now,
        },
        {
          id: "membership_workspace_e2e_account_wangshuo",
          workspaceId: "workspace_e2e",
          accountId: "account_wangshuo",
          name: "王硕",
          email: "wangshuo",
          role: "member",
          status: "active",
          createdAt: now,
          updatedAt: now,
        },
      ],
      membership: {
        id: "membership_workspace_e2e_account_owner",
        workspaceId: "workspace_e2e",
        accountId: "account_owner",
        name: "项目负责人",
        email: "owner@example.com",
        role: "owner",
        status: "active",
        createdAt: now,
        updatedAt: now,
      },
      account: {
        id: "account_owner",
        workspaceId: "workspace_e2e",
        name: "项目负责人",
        email: "owner@example.com",
        createdAt: now,
        updatedAt: now,
      },
    },
    backend: {
      ...base.backend,
      token: "e2e-token",
      serverUrl: MOCK_SERVER,
      status: "idle",
      message: "E2E 本地模式",
    },
    projects: base.projects.map((project) => ({ ...project, workspaceId: "workspace_e2e" })),
    projectMembers: base.projectMembers.map((member) => ({
      ...member,
      workspaceId: "workspace_e2e",
      accountId: "account_owner",
      email: "owner@example.com",
    })),
    tasks: [
      {
        id: "task_e2e_prd",
        title: "整理时间管理系统 PRD",
        notes: "把方法论、竞品图和旧系统升级点沉淀成可执行范围。",
        tags: ["方法论", "产品"],
        projectId: "project_starter",
        project: "TimeManage",
        creatorMemberId: "member_owner",
        primaryExecutorMemberId: "member_owner",
        collaboratorMemberIds: [],
        progressPercent: 0,
        progressNote: "",
        priority: "urgent",
        severity: "high",
        stage: "requirements",
        estimatePomodoros: 3,
        status: "committed",
        repeatRule: "none",
        subtasks: [],
        sortOrder: 10,
        actualPomodoros: 0,
        estimateHistory: [],
        createdAt: now,
        updatedAt: now,
        workspaceId: "workspace_e2e",
      },
    ],
    dailyPlans: [
      {
        id: `plan_account_owner_${todayKey}`,
        ownerAccountId: "account_owner",
        workspaceId: "workspace_e2e",
        date: todayKey,
        capacityPomodoros: 8,
        committedTaskIds: ["task_e2e_prd"],
        completedPomodoros: 0,
        suggestedTaskIds: [],
        reflection: "",
        review: {
          mood: "normal",
          wins: "",
          blockers: "",
          interruptionPattern: "",
          tomorrowFocus: "",
        },
        createdAt: now,
        updatedAt: now,
      },
    ],
    updatedAt: now,
  };
};
