import type { Task } from "./types";
import { demoIsoAt, makeDemoTask } from "./demoDataBuilders";

export const createDemoTasks = (now: string): Task[] => [
  makeDemoTask({
    id: "demo_task_today_deep",
    title: "完成工作台信息精简",
    notes: "目标是让今天只看到承诺任务、快速收集和开始专注，不再被辅助信息淹没。",
    tags: ["产品", "体验"],
    project: "TimeManage",
    priority: "urgent",
    severity: "high",
    estimatePomodoros: 3,
    actualPomodoros: 1,
    status: "in_progress",
    dueAt: demoIsoAt(0, 18),
    subtasks: [
      { id: "demo_sub_1", title: "收起辅助模块", completed: true, createdAt: now, completedAt: now },
      { id: "demo_sub_2", title: "压缩任务卡片", completed: true, createdAt: now, completedAt: now },
      { id: "demo_sub_3", title: "检查桌面布局密度", completed: false, createdAt: now },
    ],
    sortOrder: 10,
  }),
  makeDemoTask({
    id: "demo_task_today_sync",
    title: "验证本地团队后台",
    notes: "在设置页输入团队后台账号密码，确认推送、拉取和冲突提示是否能跑通。",
    tags: ["同步", "验收"],
    project: "TimeManage",
    priority: "high",
    severity: "medium",
    estimatePomodoros: 2,
    actualPomodoros: 0,
    status: "committed",
    reminderAt: demoIsoAt(0, 16),
    sortOrder: 20,
  }),
  makeDemoTask({
    id: "demo_task_today_report",
    title: "整理今日验收结论",
    notes: "汇总当前工作队列的完成情况、风险点和需要同步给团队的信息。",
    tags: ["验收", "同步"],
    project: "TimeManage",
    priority: "medium",
    severity: "medium",
    estimatePomodoros: 1,
    actualPomodoros: 0,
    status: "committed",
    sortOrder: 30,
  }),
  makeDemoTask({
    id: "demo_task_pool_calendar",
    title: "补齐排期空状态",
    tags: ["排期", "UI"],
    project: "TimeManage",
    priority: "medium",
    severity: "low",
    estimatePomodoros: 2,
    actualPomodoros: 0,
    status: "pool",
    sortOrder: 50,
  }),
  makeDemoTask({
    id: "demo_task_pool_import",
    title: "完善团队后台诊断提示",
    notes: "把服务健康、登录状态和同步结果展示得更清楚，方便快速定位团队后台问题。",
    tags: ["同步", "诊断"],
    project: "团队后台",
    priority: "high",
    severity: "high",
    estimatePomodoros: 3,
    actualPomodoros: 0,
    status: "pool",
    dueAt: demoIsoAt(1, 17),
    sortOrder: 55,
  }),
  makeDemoTask({
    id: "demo_task_pool_shortcuts",
    title: "整理快捷键帮助弹窗",
    notes: "把 Cmd+K、空格、Enter、方向键这些操作放到一个紧凑帮助面板里。",
    tags: ["效率", "键盘"],
    project: "TimeManage",
    priority: "medium",
    severity: "medium",
    estimatePomodoros: 2,
    actualPomodoros: 0,
    status: "pool",
    sortOrder: 56,
  }),
  makeDemoTask({
    id: "demo_task_pool_weekly",
    title: "准备周计划模板",
    notes: "固定整理：本周已完成、遗留风险、阻塞事项和下周安排。",
    tags: ["周会", "模板"],
    project: "团队协作",
    priority: "low",
    severity: "medium",
    estimatePomodoros: 2,
    actualPomodoros: 0,
    status: "pool",
    repeatRule: "weekly",
    sortOrder: 58,
  }),
  makeDemoTask({
    id: "demo_task_done_prd",
    title: "整理首版 PRD",
    tags: ["产品"],
    project: "TimeManage",
    priority: "high",
    severity: "high",
    estimatePomodoros: 3,
    actualPomodoros: 4,
    status: "completed",
    completedAt: demoIsoAt(-1, 17),
    sortOrder: 60,
  }),
  makeDemoTask({
    id: "demo_task_done_nav",
    title: "把左侧菜单改成应用式导航",
    tags: ["导航", "桌面应用"],
    project: "体验优化",
    priority: "high",
    severity: "medium",
    estimatePomodoros: 2,
    actualPomodoros: 2,
    status: "completed",
    completedAt: demoIsoAt(-2, 18),
    sortOrder: 70,
  }),
  makeDemoTask({
    id: "demo_task_done_focus",
    title: "完成专注页迷你计时器",
    tags: ["计时器", "专注"],
    project: "TimeManage",
    priority: "high",
    severity: "high",
    estimatePomodoros: 4,
    actualPomodoros: 5,
    status: "completed",
    completedAt: demoIsoAt(-5, 16),
    sortOrder: 80,
  }),
  makeDemoTask({
    id: "demo_task_done_review",
    title: "设计验收说明字段",
    tags: ["验收", "方法论"],
    project: "TimeManage",
    priority: "medium",
    severity: "medium",
    estimatePomodoros: 2,
    actualPomodoros: 2,
    status: "completed",
    completedAt: demoIsoAt(-8, 18),
    sortOrder: 90,
  }),
];
