import type { Task } from "./types";
import { demoIsoAt, makeDemoTask } from "./demoDataBuilders";

export const createDemoTasks = (now: string): Task[] => [
  makeDemoTask({
    id: "demo_task_today_deep",
    title: "完成工作台信息精简",
    notes: "目标是让今天只看到承诺任务、快速收集和开始专注，不再被辅助信息淹没。",
    tags: ["产品", "体验"],
    project: "TimeManage",
    priority: "urgent",
    severity: "high",
    estimatePomodoros: 3,
    actualPomodoros: 1,
    status: "in_progress",
    dueAt: demoIsoAt(0, 18),
    subtasks: [
      { id: "demo_sub_1", title: "收起辅助模块", completed: true, createdAt: now, completedAt: now },
      { id: "demo_sub_2", title: "压缩任务卡片", completed: true, createdAt: now, completedAt: now },
      { id: "demo_sub_3", title: "检查桌面布局密度", completed: false, createdAt: now },
    ],
    sortOrder: 10,
  }),
  makeDemoTask({
    id: "demo_task_today_sync",
    title: "验证本地团队后台",
    notes: "在设置页输入团队后台账号密码，确认推送、拉取和冲突提示是否能跑通。",
    tags: ["同步", "验收"],
    project: "TimeManage",
    priority: "high",
    severity: "medium",
    estimatePomodoros: 2,
    actualPomodoros: 0,
    status: "committed",
    reminderAt: demoIsoAt(0, 16),
    sortOrder: 20,
  }),
  makeDemoTask({
    id: "demo_task_today_report",
    title: "看一遍自律报告",
    notes: "重点看完成率、估算偏差、中断热区和容量建议。",
    tags: ["复盘", "报告"],
    project: "个人节奏",
    priority: "medium",
    severity: "medium",
    estimatePomodoros: 1,
    actualPomodoros: 0,
    status: "committed",
    sortOrder: 30,
  }),
  makeDemoTask({
    id: "demo_task_pool_calendar",
    title: "补齐日历月视图空状态",
    tags: ["日历", "UI"],
    project: "TimeManage",
    priority: "medium",
    severity: "low",
    estimatePomodoros: 2,
    actualPomodoros: 0,
    status: "pool",
    sortOrder: 50,
  }),
  makeDemoTask({
    id: "demo_task_pool_import",
    title: "完善数据导入前的备份提示",
    notes: "导入 JSON 前自动创建恢复点，并在结果页展示任务、番茄、计划的增量。",
    tags: ["数据", "备份"],
    project: "数据安全",
    priority: "high",
    severity: "high",
    estimatePomodoros: 3,
    actualPomodoros: 0,
    status: "pool",
    dueAt: demoIsoAt(1, 17),
    sortOrder: 55,
  }),
  makeDemoTask({
    id: "demo_task_pool_shortcuts",
    title: "整理快捷键帮助弹窗",
    notes: "把 Cmd+K、空格、Enter、方向键这些操作放到一个紧凑帮助面板里。",
    tags: ["效率", "键盘"],
    project: "TimeManage",
    priority: "medium",
    severity: "medium",
    estimatePomodoros: 2,
    actualPomodoros: 0,
    status: "pool",
    sortOrder: 56,
  }),
  makeDemoTask({
    id: "demo_task_pool_weekly",
    title: "准备周复盘模板",
    notes: "固定回答：本周兑现率、低估任务、最常见中断、下周容量。",
    tags: ["周复盘", "模板"],
    project: "个人节奏",
    priority: "low",
    severity: "medium",
    estimatePomodoros: 2,
    actualPomodoros: 0,
    status: "pool",
    repeatRule: "weekly",
    sortOrder: 58,
  }),
  makeDemoTask({
    id: "demo_task_done_prd",
    title: "整理首版 PRD",
    tags: ["产品"],
    project: "TimeManage",
    priority: "high",
    severity: "high",
    estimatePomodoros: 3,
    actualPomodoros: 4,
    status: "completed",
    completedAt: demoIsoAt(-1, 17),
    sortOrder: 60,
  }),
  makeDemoTask({
    id: "demo_task_done_nav",
    title: "把左侧菜单改成应用式导航",
    tags: ["导航", "桌面应用"],
    project: "体验优化",
    priority: "high",
    severity: "medium",
    estimatePomodoros: 2,
    actualPomodoros: 2,
    status: "completed",
    completedAt: demoIsoAt(-2, 18),
    sortOrder: 70,
  }),
  makeDemoTask({
    id: "demo_task_done_focus",
    title: "完成专注页迷你计时器",
    tags: ["计时器", "专注"],
    project: "TimeManage",
    priority: "high",
    severity: "high",
    estimatePomodoros: 4,
    actualPomodoros: 5,
    status: "completed",
    completedAt: demoIsoAt(-5, 16),
    sortOrder: 80,
  }),
  makeDemoTask({
    id: "demo_task_done_review",
    title: "设计日终回顾字段",
    tags: ["复盘", "方法论"],
    project: "个人节奏",
    priority: "medium",
    severity: "medium",
    estimatePomodoros: 2,
    actualPomodoros: 2,
    status: "completed",
    completedAt: demoIsoAt(-8, 18),
    sortOrder: 90,
  }),
];
