import type { TimeManageClient } from "./client.js";

type FunctionKeys<T> = {
  [K in keyof T]: T[K] extends (...args: never[]) => unknown ? K : never;
}[keyof T];

export const cliCapabilityCommands = {
  health: "health",
  getBackendDiagnostics: "doctor",
  getCurrentAccount: "account show",
  listWorkspaces: "workspace list",
  switchWorkspace: "workspace switch",
  createWorkspace: "workspace create",
  updateWorkspace: "workspace update",
  updateWorkspaceMembership: "workspace member update",
  listPlatformAccounts: "account platform list",
  createPlatformAccount: "account platform create",
  updatePlatformAccount: "account platform update",
  disablePlatformAccount: "account platform disable",
  updatePlatformAccountPassword: "account platform password",
  listWorkspaceInvitations: "workspace invitation list",
  inviteWorkspaceMember: "workspace invitation invite",
  acceptWorkspaceInvitation: "workspace invitation accept",
  deleteWorkspaceInvitation: "workspace invitation delete",
  listProjectInvitations: "project invitation list",
  inviteProjectMember: "project invitation invite",
  acceptProjectInvitation: "project invitation accept",
  deleteProjectInvitation: "project invitation delete",
  createMemberAccount: "account member create",
  updateMemberAccount: "account member update",
  listProjects: "project list",
  search: "search",
  getProjectOverview: "project show",
  createProject: "project create",
  updateProject: "project update",
  archiveProject: "project archive",
  restoreProject: "project restore",
  listMembers: "project member list",
  createMember: "project member create",
  updateMember: "project member update",
  deleteMember: "project member delete",
  bindMemberToProject: "project member bind",
  updateProjectMember: "project member update",
  unbindProjectMember: "project member unbind",
  listRiskTasks: "project risks",
  listTasks: "task list",
  getTask: "task show",
  createTask: "task create",
  batchCreateTasks: "task create-batch",
  updateTask: "task update",
  deleteTask: "task delete",
  assignTask: "task assign",
  batchAssignTasks: "task assign-batch",
  setTaskStatus: "task status",
  updateTaskProgress: "task progress",
  splitTask: "task split",
  getTodayPlan: "plan show",
  getTodayWorkbench: "plan workbench",
  addTaskToToday: "plan add",
  batchAddTasksToToday: "plan add-batch",
  removeTaskFromToday: "plan remove",
  moveTodayTask: "plan move",
  scheduleTaskForDate: "plan schedule",
  startTask: "work start",
  pauseWorkSession: "work pause",
  resumeWorkSession: "work resume",
  finishWorkSession: "work finish",
  getActiveWork: "work active",
  recordInterruption: "work interrupt",
  submitTaskReview: "review submit",
  acceptTaskReview: "review accept",
  returnTaskReview: "review return",
  listPendingReviews: "review pending",
  getMemberStatus: "member status",
  getDailySummary: "daily summary",
  updateDailyReview: "daily review",
  getSettings: "settings show",
  updateSettings: "settings update",
  listTaskTemplates: "template list",
  saveTaskTemplate: "template save",
  deleteTaskTemplate: "template delete",
  instantiateTaskTemplate: "template instantiate",
} satisfies Record<FunctionKeys<TimeManageClient>, string>;
